development:
  adapter: postgresql
  encoding: unicode
  database: bw-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bw-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bw-prod
  pool: 5
  host: localhost
  username: action
  password: